### ISSUE TITLE
calls to 'roster' will hang if one of them gets interrupted. (iqd hanging?)

### ISSUE THREAD

**Issue by earboxer** [younix/sj#22]
I originally noticed this while writing a shell-implementation of [XEP-0401](https://xmpp.org/extensions/xep-0401.html) (client-side generate invitations), but the bug affects roster just as well.

# Reproducing this bug

`watch -n .1 roster` then press ^C to interrupt it while it's running

running `roster` again will hang interminably (as well as any other command which expects things to be written to an `<iq>` id-named FIFO), although with `-D` debug mode, you can see the requests and responses in the log.

Restarting everything is the only way to fix it (presumably `iqd` is hanging -- or otherwise not functioning correctly.)

**Comment by younix** [comment]
I made a fix in iqd for hanging pipes. Could you tests this for your usecase?

Thanks!

**Comment by earboxer** [comment]
I was still able to reproduce this after pulling the change.

**Comment by younix** [comment]
Ok, I guess you are using it on Linux.
I fixed it in another way.

Does it work for you?

**Comment by earboxer** [comment]
Yes, looks like that fixed it, thanks!

**Comment by younix** [comment]
fixed
